jwt:
  secret: aXv7j3tR8kL9mQp2sV5y7x9A1zC4E7H0bW3cZ6u8oP1dF4rT5nJ9iK2lO0q
  access-token-expiration: 86400000
  
kafka:
  topics:
    # Task events
    task-created: "task.created"
    task-updated: "task.updated"
    task-subscribed: "task.subscribed"
    task-unsubscribed: "task.unsubscribed"
    task-completed: "task.completed"
    task-deleted: "task.deleted"
    task-status-updated: "task.status.updated"
    task-assignees-updated: "task.assignees.updated"
    
    # Attachment events
    attachment-added: "attachment.added"
    attachment-deleted: "attachment.deleted"
    
    # Comment events
    comment-created: "comment.created"
    comment-updated: "comment.updated"
    comment-deleted: "comment.deleted"

    # Auth events
    user-registered: "user.registered"
    user-role-updated: "user.role.updated"
    user-login-success: "auth.login.success"
    user-login-failed: "auth.login.failed"
    
    # User and events
    user-created: "user.created"
    user-deleted: "user.deleted"
    user-profile-updated: "user.profile.updated"
    
    
